name: scrape_application
description: "A new Flutter project."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.25.4
  flutter_animate: ^4.5.0
  go_router: ^13.2.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  provider: ^6.1.1
  firebase_auth: ^4.17.6
  url_launcher: ^6.2.5
  firebase_ui_auth: ^1.13.1
  google_fonts: ^6.2.0
  cloud_firestore: ^4.15.6
  lottie: ^3.1.0
  shared_preferences: ^2.2.2
  flutter_keyboard_visibility: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/

  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
